### ISSUE TITLE
Error (php 7 , ubuntu 16.04 docker ) 

### ISSUE THREAD

**Issue by liorkesos** [linnovate/elementor-drupal#18]
When running (in docker on mac  , 128MB php) I get the next error below.
I see this error when clicking on the tab elementor...
[Tue Aug 07 20:16:36.048719 2018] [:error] [pid 145] [client 172.18.0.1:37238] Error: Call to a member function id() on null in /var/www/html/web/modules/contrib/elementor/elementor.module on line 75 #0 /var/www/html/web/core/lib/Drupal/Core/Theme/ThemeManager.php(287): elementor_preprocess_elementor_field(Array, 'elementor_field', Array)\n#1 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(437): Drupal\\Core\\Theme\\ThemeManager->render('elementor_field', Array)\n#2 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(195): Drupal\\Core\\Render\\Renderer->doRender(Array, false)\n#3 /var/www/html/web/core/lib/Drupal/Core/Template/TwigExtension.php(490): Drupal\\Core\\Render\\Renderer->render(Array)\n#4 /var/www/html/web/sites/default/files/php/twig/5b69fbb934b4e_field.html.twig_sg0aNDZNrB2qJXZQKh1ByVo-x/NQgTDTz9KG1VSZ_0-umkCKsp36VEUQ36c98LMuT7LUk.php(91): Drupal\\Core\\Template\\TwigExtension->escapeFilter(Object(Drupal\\Core\\Template\\TwigEnvironment), Array, 'html', NULL, true)\n#5 /var/www/html/vendor/twig/twig/lib/Twig/Template.php(432): __TwigTemplate_5b03bca200df2d5ba1ca47d2e222b86347639abbdcd0d8d587ebad065efba4c8->doDisplay(Array, Array)\n#6 /var/www/html/vendor/twig/twig/lib/Twig/Template.php(403): Twig_Template->displayWithErrorHandling(Array, Array)\n#7 /var/www/html/web/sites/default/files/php/twig/5b69fbb934b4e_field--text.html.twig_QRokRSh6FCHqQzooG_1XDDBRv/4JxASR4Q7ibKfKh2KtzG3BfGJBBBrgAgvltJwAbUluc.php(50): Twig_Template->display(Array, Array)\n#8 /var/www/html/vendor/twig/twig/lib/Twig/Template.php(432): __TwigTemplate_e31b6bd3d1b2c96162eebdb14334b21ab61f4d491b59303bdc56cb8e3a6b4a4a->doDisplay(Array, Array)\n#9 /var/www/html/vendor/twig/twig/lib/Twig/Template.php(403): Twig_Template->displayWithErrorHandling(Array, Array)\n#10 /var/www/html/web/sites/default/files/php/twig/5b69fbb934b4e_field--text-with-summary._gLNSZGKby7XjpK24cB7UxUBGx/S1PAZVX5qK3sDHKwKVqFYLtVCCj3plorYfiSvi248fo.php(47): Twig_Template->display(Array, Array)\n#11 /var/www/html/vendor/twig/twig/lib/Twig/Template.php(432): __TwigTemplate_d27e7dff4c233dd750e0d55a24ef9defe7e7849370d70ec8406fd8d208d45386->doDisplay(Array, Array)\n#12 /var/www/html/vendor/twig/twig/lib/Twig/Template.php(403): Twig_Template->displayWithErrorHandling(Array, Array)\n#13 /var/www/html/vendor/twig/twig/lib/Twig/Template.php(411): Twig_Template->display(Array)\n#14 /var/www/html/web/core/themes/engines/twig/twig.engine(64): Twig_Template->render(Array)\n#15 /var/www/html/web/core/lib/Drupal/Core/Theme/ThemeManager.php(384): twig_render_template('core/themes/cla...', Array)\n#16 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(437): Drupal\\Core\\Theme\\ThemeManager->render('field', Array)\n#17 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(450): Drupal\\Core\\Render\\Renderer->doRender(Array)\n#18 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(195): Drupal\\Core\\Render\\Renderer->doRender(Array, false)\n#19 /var/www/html/web/core/lib/Drupal/Core/Template/TwigExtension.php(490): Drupal\\Core\\Render\\Renderer->render(Array)\n#20 /var/www/html/web/sites/default/files/php/twig/5b69fbb934b4e_node.html.twig_P4BQvAKBFovvw9i7naZmbh0bQ/q3gpxNOP7iE3M3smLDOiKFY-qSRszZIjybQyTU_TOCQ.php(114): Drupal\\Core\\Template\\TwigExtension->escapeFilter(Object(Drupal\\Core\\Template\\TwigEnvironment), Array, 'html', NULL, true)\n#21 /var/www/html/vendor/twig/twig/lib/Twig/Template.php(432): __TwigTemplate_4ae59022820823361d314fdb0db03eda142ac3295eb1399a7323e963e3d3bf5a->doDisplay(Array, Array)\n#22 /var/www/html/vendor/twig/twig/lib/Twig/Template.php(403): Twig_Template->displayWithErrorHandling(Array, Array)\n#23 /var/www/html/vendor/twig/twig/lib/Twig/Template.php(411): Twig_Template->display(Array)\n#24 /var/www/html/web/core/themes/engines/twig/twig.engine(64): Twig_Template->render(Array)\n#25 /var/www/html/web/core/lib/Drupal/Core/Theme/ThemeManager.php(384): twig_render_template('core/themes/bar...', Array)\n#26 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(437): Drupal\\Core\\Theme\\ThemeManager->render('node', Array)\n#27 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(195): Drupal\\Core\\Render\\Renderer->doRender(Array, false)\n#28 /var/www/html/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(226): Drupal\\Core\\Render\\Renderer->render(Array, false)\n#29 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(582): Drupal\\Core\\Render\\MainContent\\HtmlRenderer->Drupal\\Core\\Render\\MainContent\\{closure}()\n#30 /var/www/html/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(227): Drupal\\Core\\Render\\Renderer->executeInRenderContext(Object(Drupal\\Core\\Render\\RenderContext), Object(Closure))\n#31 /var/www/html/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(117): Drupal\\Core\\Render\\MainContent\\HtmlRenderer->prepare(Array, Object(Symfony\\Component\\HttpFoundation\\Request), Object(Drupal\\Core\\Routing\\CurrentRouteMatch))\n#32 /var/www/html/web/core/lib/Drupal/Core/EventSubscriber/MainContentViewSubscriber.php(90): Drupal\\Core\\Render\\MainContent\\HtmlRenderer->renderResponse(Array, Object(Symfony\\Component\\HttpFoundation\\Request), Object(Drupal\\Core\\Routing\\CurrentRouteMatch))\n#33 [internal function]: Drupal\\Core\\EventSubscriber\\MainContentViewSubscriber->onViewRenderArray(Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseForControllerResultEvent), 'kernel.view', Object(Drupal\\Component\\EventDispatcher\\ContainerAwareEventDispatcher))\n#34 /var/www/html/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(111): call_user_func(Array, Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseForControllerResultEvent), 'kernel.view', Object(Drupal\\Component\\EventDispatcher\\ContainerAwareEventDispatcher))\n#35 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(156): Drupal\\Component\\EventDispatcher\\ContainerAwareEventDispatcher->dispatch('kernel.view', Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseForControllerResultEvent))\n#36 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#37 /var/www/html/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#38 /var/www/html/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\\Core\\StackMiddleware\\Session->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#39 /var/www/html/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(99): Drupal\\Core\\StackMiddleware\\KernelPreHandle->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#40 /var/www/html/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(78): Drupal\\page_cache\\StackMiddleware\\PageCache->pass(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#41 /var/www/html/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\\page_cache\\StackMiddleware\\PageCache->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#42 /var/www/html/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\\Core\\StackMiddleware\\ReverseProxyMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#43 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\\Core\\StackMiddleware\\NegotiationMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#44 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(666): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#45 /var/www/html/web/index.php(19): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#46 {main}, referer: http://localhost/node/add/article

**Comment by liorkesos** [comment]
Not a bug related to #19
